### PR TITLE
Add import path for engo/common. Fixes EngoEngine/engo#344.

### LINKED ISSUE #344: GoDoc: Common package is missing
https://godoc.org/engo.io/engo/ is reachable but https://godoc.org/engo.io/engo/common is not.

This is the first time I've come across this issue, so I am opening it here for research since I discovered it on this project. It could be related to the custom go get source you have or it might be related to GoDoc it's self.

### PR DESCRIPTION
**Pull request by mewmew**
I hope this should be enough to fix EngoEngine/engo#344. Otherwise, we may try something else.

### CODE REVIEW

**Comment by mewmew** [comment]
@otraore As you played around with this before, would you mind checking if the above PR may resolve the issue?

Wish you a lovely 2017 : )

Cheerful wishes from a snow-clad Sweden : )
/u

**Comment by mewmew** [comment]
For reference, https://godoc.org/engo.io/engo/common currently gives a 404.

**Comment by otraore** [comment]
I think I already tried this in [this](https://github.com/EngoEngine/engoengine.github.io/commit/a6bd423c0ae4237ea9c79fe8ca2ce97415df4890) commit, but I'll double check once I'm able to. As far as I know it didn't work when I tried it.

**Comment by Noofbiz** [comment]
Ping ^_^

**Comment by paked** [comment]
LGTM

**Pull request merged**
